---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: list_infra_providers
    inherits: 
    description: 
  fields:
  - execute:
      value: list_infra_providers
