---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_Task_Complete
    inherits: 
    description: 
  fields:
  - rel4:
      value: "/System/event_handlers/event_action_refresh_sync?target=src_vm"
  - rel5:
      value: "/System/event_handlers/event_action_policy?target=src_vm&policy_event=vm_reconfigure&param="
