---
object_type: method
version: 1.0
object:
  attributes:
    name: list_infra_providers
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
